# 로컬 환경, 개발 PC에서의 Docker (프로덕션용이 아님)
version: "3.9"
services: 
  webapp:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT_EXTERNAL}:${APP_PORT}"
    volumes:
      - ./web:/app/web
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/logs:/var/log/apache2
      - ./scripts:/app/scripts
      # - ./composer.json:/app/composer.json
      # - ./web/composer.lock:/app/composer.lock
    entrypoint: /bin/bash /app/docker-entrypoint.sh
    depends_on:
      - db
  db:
    image: mariadb:10.6
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - ${DB_PORT_EXTERNAL}:${DB_PORT}
    volumes:
      - maindb:/var/lib/mysql
      - ./scripts:/app/scripts
volumes:
  maindb:
